
package org.chamerling.heroku.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.heroku.chamerling.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param via
     * @param pil
     * @param saldoKartu
     * @param nominal
     * @param idKartu
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ubahSaldo", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.UbahSaldo")
    @ResponseWrapper(localName = "ubahSaldoResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.UbahSaldoResponse")
    public Boolean ubahSaldo(
        @WebParam(name = "pil", targetNamespace = "")
        int pil,
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal,
        @WebParam(name = "saldoKartu", targetNamespace = "")
        int saldoKartu,
        @WebParam(name = "via", targetNamespace = "")
        String via);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.heroku.chamerling.org/", className = "org.chamerling.heroku.service.SayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
