
package com.servermerchant.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://webservice.servermerchant.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns com.servermerchant.webservice.ArrayTransaksi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListTransaksi", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetListTransaksi")
    @ResponseWrapper(localName = "getListTransaksiResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetListTransaksiResponse")
    public ArrayTransaksi getListTransaksi();

    /**
     * 
     * @param waktu
     * @return
     *     returns com.servermerchant.webservice.ArrayTransaksiBarang
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaksiBarangByWaktu", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetTransaksiBarangByWaktu")
    @ResponseWrapper(localName = "getTransaksiBarangByWaktuResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetTransaksiBarangByWaktuResponse")
    public ArrayTransaksiBarang getTransaksiBarangByWaktu(
        @WebParam(name = "waktu", targetNamespace = "")
        String waktu);

    /**
     * 
     * @param nominal
     * @param idKartu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksi", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksi")
    @ResponseWrapper(localName = "addTransaksiResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksiResponse")
    public String addTransaksi(
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal);

    /**
     * 
     * @param waktu
     * @param nominal
     * @param idKartu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksiParamWaktu", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksiParamWaktu")
    @ResponseWrapper(localName = "addTransaksiParamWaktuResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksiParamWaktuResponse")
    public String addTransaksiParamWaktu(
        @WebParam(name = "waktu", targetNamespace = "")
        String waktu,
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal);

    /**
     * 
     * @return
     *     returns com.servermerchant.webservice.ArrayBarang
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListBarang", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetListBarang")
    @ResponseWrapper(localName = "getListBarangResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.GetListBarangResponse")
    public ArrayBarang getListBarang();

    /**
     * 
     * @param waktu
     * @param idBarang
     * @param jumlah
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksiBarangJumlah", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksiBarangJumlah")
    @ResponseWrapper(localName = "addTransaksiBarangJumlahResponse", targetNamespace = "http://webservice.servermerchant.com/", className = "com.servermerchant.webservice.AddTransaksiBarangJumlahResponse")
    public Boolean addTransaksiBarangJumlah(
        @WebParam(name = "waktu", targetNamespace = "")
        String waktu,
        @WebParam(name = "idBarang", targetNamespace = "")
        String idBarang,
        @WebParam(name = "jumlah", targetNamespace = "")
        String jumlah);

}
