
package org.chamerling.heroku.servicepaymentgateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param waktu
     * @param noCc
     * @return
     *     returns org.chamerling.heroku.servicepaymentgateway.Transaksi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaksi", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetTransaksi")
    @ResponseWrapper(localName = "getTransaksiResponse", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetTransaksiResponse")
    public Transaksi getTransaksi(
        @WebParam(name = "noCc", targetNamespace = "")
        String noCc,
        @WebParam(name = "waktu", targetNamespace = "")
        XMLGregorianCalendar waktu);

    /**
     * 
     * @param noCc
     * @return
     *     returns org.chamerling.heroku.servicepaymentgateway.ArrayTransaksi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListTransaksi", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetListTransaksi")
    @ResponseWrapper(localName = "getListTransaksiResponse", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetListTransaksiResponse")
    public ArrayTransaksi getListTransaksi(
        @WebParam(name = "noCc", targetNamespace = "")
        String noCc);

    /**
     * 
     * @param noCc
     * @param nominal
     * @param keBank
     * @param dariBank
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksi", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.AddTransaksi")
    @ResponseWrapper(localName = "addTransaksiResponse", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.AddTransaksiResponse")
    public Boolean addTransaksi(
        @WebParam(name = "noCc", targetNamespace = "")
        String noCc,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal,
        @WebParam(name = "dariBank", targetNamespace = "")
        String dariBank,
        @WebParam(name = "keBank", targetNamespace = "")
        String keBank);

    /**
     * 
     * @return
     *     returns org.chamerling.heroku.servicepaymentgateway.ArrayNoCc
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNoCc", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetNoCc")
    @ResponseWrapper(localName = "getNoCcResponse", targetNamespace = "http://servicepaymentgateway.heroku.chamerling.org/", className = "org.chamerling.heroku.servicepaymentgateway.GetNoCcResponse")
    public ArrayNoCc getNoCc();

}
