
package org.chamerling.heroku.servicemerchant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://servicemerchant.heroku.chamerling.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param nominal
     * @param idKartu
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksi", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.AddTransaksi")
    @ResponseWrapper(localName = "addTransaksiResponse", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.AddTransaksiResponse")
    public String addTransaksi(
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal);

    /**
     * 
     * @return
     *     returns org.chamerling.heroku.servicemerchant.ArrayBarang
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListBarang", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetListBarang")
    @ResponseWrapper(localName = "getListBarangResponse", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetListBarangResponse")
    public ArrayBarang getListBarang();

    /**
     * 
     * @param waktu
     * @param idBarang
     * @param jumlah
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTransaksiBarangJumlah", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.AddTransaksiBarangJumlah")
    @ResponseWrapper(localName = "addTransaksiBarangJumlahResponse", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.AddTransaksiBarangJumlahResponse")
    public Boolean addTransaksiBarangJumlah(
        @WebParam(name = "waktu", targetNamespace = "")
        String waktu,
        @WebParam(name = "idBarang", targetNamespace = "")
        String idBarang,
        @WebParam(name = "jumlah", targetNamespace = "")
        String jumlah);

    /**
     * 
     * @return
     *     returns org.chamerling.heroku.servicemerchant.ArrayTransaksi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListTransaksi", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetListTransaksi")
    @ResponseWrapper(localName = "getListTransaksiResponse", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetListTransaksiResponse")
    public ArrayTransaksi getListTransaksi();

    /**
     * 
     * @param waktu
     * @return
     *     returns org.chamerling.heroku.servicemerchant.ArrayTransaksiBarang
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransaksiBarangByWaktu", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetTransaksiBarangByWaktu")
    @ResponseWrapper(localName = "getTransaksiBarangByWaktuResponse", targetNamespace = "http://servicemerchant.heroku.chamerling.org/", className = "org.chamerling.heroku.servicemerchant.GetTransaksiBarangByWaktuResponse")
    public ArrayTransaksiBarang getTransaksiBarangByWaktu(
        @WebParam(name = "waktu", targetNamespace = "")
        String waktu);

}
