
package org.chamerling.heroku.servicesismic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://servicesismic.heroku.chamerling.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param idKartu
     * @return
     *     returns org.chamerling.heroku.servicesismic.Kartu
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoKartu", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.GetInfoKartu")
    @ResponseWrapper(localName = "getInfoKartuResponse", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.GetInfoKartuResponse")
    public Kartu getInfoKartu(
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu);

    /**
     * 
     * @param idKartu
     * @return
     *     returns org.chamerling.heroku.servicesismic.ArrayTransaksi
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListTransaksi", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.GetListTransaksi")
    @ResponseWrapper(localName = "getListTransaksiResponse", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.GetListTransaksiResponse")
    public ArrayTransaksi getListTransaksi(
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu);

    /**
     * 
     * @param via
     * @param pil
     * @param saldoKartu
     * @param nominal
     * @param idKartu
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ubahSaldo", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.UbahSaldo")
    @ResponseWrapper(localName = "ubahSaldoResponse", targetNamespace = "http://servicesismic.heroku.chamerling.org/", className = "org.chamerling.heroku.servicesismic.UbahSaldoResponse")
    public Boolean ubahSaldo(
        @WebParam(name = "pil", targetNamespace = "")
        int pil,
        @WebParam(name = "idKartu", targetNamespace = "")
        String idKartu,
        @WebParam(name = "nominal", targetNamespace = "")
        int nominal,
        @WebParam(name = "saldoKartu", targetNamespace = "")
        int saldoKartu,
        @WebParam(name = "via", targetNamespace = "")
        String via);

}
